### ISSUE TITLE
Claimed tx's do not go to my wallet

### ISSUE THREAD

**Issue by skatermikale** [jontstaz/BSC-DEX-Prediction-Bot#1]
Wallet slowly drains even after multiple wins.

**Comment by jontstaz** [comment]
Hmm this shouldn't happen. It will claim the winnings after each round that is won but sometimes there may be a delay. I noticed you closed this issue so I assume you resolved whatever the problem was?

**Comment by skatermikale** [comment]
Thanks for the response. Yes I did close because I noticed the delay in claimed profit's showing up in the wallet.
Ran the bot for several hours and cannot seem to achieve above 50% win ratio.

**Comment by jontstaz** [comment]
Have you pulled the latest update from today? I adjusted the weighting of the 5min and 1min to give them equal weighting now. In my experience it performs better like this.

**Comment by skatermikale** [comment]
I'll give it a shot now!

**Comment by skatermikale** [comment]
Winning about 68.75% now.

**Comment by jontstaz** [comment]
> 
> 
> Winning about 68.75% now.

Awesome to hear! Seems like my formula update was for the best.
