### ISSUE TITLE
3min

### ISSUE THREAD

**Issue by chestern3405** [jontstaz/BSC-DEX-Prediction-Bot#2]
is there a way to add a 3min interval?

**Comment by jontstaz** [comment]
Do you mean a 3min chart interval for TA? Unfortunately it's not possible. TradingView only has 1min, 5min, 15min, 30min, 1hr, 2hrs, 4hrs, etc..

**Comment by chestern3405** [comment]
TradingView has 3min on their website


<img width="316" alt="Screen Shot 2021-11-22 at 6 45 55 PM" src="https://user-images.githubusercontent.com/87405860/142955894-4d6019fe-3b44-41d9-9bce-66bb7c06c369.png">

**Comment by jontstaz** [comment]
Sorry, to clarify the bot uses a library which specially call the TradingView Screener pages, not the charts.

TradingView Screener doesn't have a 3m option:

![Screenshot_20211125-000310.jpg](https://user-images.githubusercontent.com/6379873/143243681-5c765608-7312-4c56-a88a-80bbea8f0a68.jpg)
